services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4567:4566' # LocalStack Gateway
      - '4610-4659:4610-4659' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns
      LOCALSTACK_HOST: 127.0.0.1
      EXTERNAL_SERVICE_PORTS_START: 4610
      EXTERNAL_SERVICE_PORTS_END: 4659
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
      - ./compose/IAHW-896I-FTN9.pdf:/tmp/IAHW-896I-FTN9.pdf
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - ahwr-local

  mongodb:
    image: mongo:7.0.28
    networks:
      - ahwr-local
    ports:
      - '27018:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  ahwr-message-generator-backend:
    build:
      context: .
      target: development
    ports:
      - '3007:3001'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - path: 'compose/aws.env'
        required: true
      - path: './.env'
        required: false
    environment:
      PORT: 3001
      NODE_ENV: development
      AWS_ENDPOINT_URL: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
      USE_PRETTY_PRINT: true
      APPLICATION_API_URI: "http://appstub:5678/api"
      MESSAGE_GENERATOR_QUEUE_URL: "http://sqs.eu-west-2.127.0.0.1:4566/000000000000/ahwr_message_generator_queue"
      MESSAGE_REQUEST_TOPIC_ARN: "arn:aws:sns:eu-west-2:000000000000:ahwr_message_request"
      DOCUMENT_BUCKET_NAME: ahwr-documents
      BACKOFFICE_UI_API_KEY: ${BACKOFFICE_UI_API_KEY:-446dcdbe-e02c-4d16-a266-001bbbd5f089}
      APPLICATION_BACKEND_API_KEY: ${APPLICATION_BACKEND_API_KEY:-fab78725-3037-45ed-ad2e-28cd86e70ff8}
    networks:
      - ahwr-local
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  appstub:
    image: hashicorp/http-echo
    command: [ "-text={\"name\":\"cadburys world\", \"farmerName\":\"Big Dave\", \"email\":\"nowhere@anywhere.com\", \"orgEmail\":\"org@anywhere.com\"}" ]
    ports:
      - "8084:5678"
    networks:
      - ahwr-local

################################################################################

volumes:
  mongodb-data:

networks:
  ahwr-local:
    external: true
    name: ahwr-local
